### ISSUE TITLE
Bowls, wood tool, and stone tool recipes no longer work.

### ISSUE THREAD

**Issue by ZariusCorten** [DevDyna/IronBerry#25] opened 2024-07-02 00:13 UTC
### Core Section

- [X] I have searched for this issue on this repository
- [X] This bug persist and I need help
- [X] I'm using the latest version of this project
- [X] I'm try to reinstall it on a clean instance (common issue)

### Environment

Singleplayer/Local | NO LAN

### Modpack Version

0.9.c HOTFIX

### Description

Bowls, wood tool, and stone tool recipes no longer work. (I started a new game for shits and giggles.)

### Procedure

N/A

### Additional things

N/A

**Comment by DevDyna** [comment] 2024-07-02 13:53
fixed on https://github.com/DevDyna/IronBerry/commit/498af8ebd58f3d15b7d7a3127196ac27d2727372
(probably was caused by filters so maybe one day will come back and i need to remove them)

**Closed by DevDyna** 2024-07-02 13:53 UTC
Labels: bug, need support
